### PR TITLE
Use Thread.current instead of a class_attribute for thread safety

### PR DESCRIPTION
**Pull request by jdurand**
```class_attribute``` is not thread safe _by design_ (https://github.com/rails/rails/issues/14021). This commit enables storing the pusherable trigger state in the ```Thread.current``` hash for thread safety.

I also took the liberty to do a bit of refactoring.

### CODE REVIEW

**Comment by tonycoco** [comment]
I'd merge, but the tests are blown up. Got a minute to fix them?

**Comment by jdurand** [comment]
Ruby 1.9 blows up because it doesn't handle thread variables the same way as ruby 2.0+ (thread_variable_get/thread_variable_set were not implemented yet). Support for 1.9 has ended last month. Do you still need to support it?
How about a version bump and a mention in the README?

**Comment by tonycoco** [comment]
Sounds good. I'll do that after I merge this and fix the Travis builds to forget about 1.9.3

**Comment by jdurand** [comment]
The feature/paranoia branch contains all of these commits, so this pull request doesn't need to be merged as well.

**Comment by tonycoco** [comment]
Ok cool

**Pull request merged**
