### PR TITLE
Feature/paranoia

### PR DESCRIPTION
**Pull request by jdurand**
Add support for paranoid model destroys (handles destruction through paranoia gem which actually updates deleted_at column)

### CODE REVIEW

**Comment by tonycoco** [comment]
Great commit, but again, broke something with the tests

**Comment by tonycoco** [comment]
Looks like it might be Ruby 1.9.3's problem... might need to drop support for it.

**Comment by tonycoco** [comment]
Also, could mention support for paranoia in the README.md too :)

**Comment by jdurand** [comment]
Oops just realized that I hadn't isolated this pull request from the previous one. 
I'll add the README mention.

Do you want me to take care of the version bump?

**Comment by tonycoco** [comment]
I can bump once all the pull requests are fixed and merged.

**Comment by tonycoco** [comment]
Release 1.3.0... Thanks for your help! I'll add you as an owner to this repo so you can move stuff forward if you'd like.

**Comment by jdurand** [comment]
Good, thanks!

**Pull request merged**
